---
- name: "Create root directory"
  ansible.builtin.file:
    path: "/compose/nginx/{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - ''

- name: "Create applicative directory"
  ansible.builtin.file:
    path: "/compose/nginx/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - bind/
    - bind/cert/
    - bind/conf.d/
    - bind/root/
    - bind/root/certbot/
    - data/
    - data/script/

- name: "Copy nginx conf"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: "/compose/nginx/bind/nginx.conf"
    mode: '0644'

- name: "Copy nginx domains confs"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/domain/{{ item }}.conf"
    dest: "/compose/nginx/bind/conf.d/{{ item }}.conf"
    mode: '0644'
  loop:
    - aloeil.ddns.net
    - aloeil.duckdns.org
    - WC.aloeil.duckdns.org

- name: "Create compose file"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "/compose/nginx/docker-compose.yml"
    mode: '0600'

- name: "Create certbot management scripts"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/script/{{ item }}"
    dest: "/compose/nginx/data/script/{{ item }}"
    mode: '0754'
  loop:
    - aloeil-certbot-create.sh
    - aloeil-certbot-renew.sh

- name: "Create certbot hook scripts"
  ansible.builtin.template:
    src: "script/{{ item }}.j2"
    dest: "/compose/nginx/data/script/{{ item }}"
    mode: '0754'
  loop:
    - aloeil-duckdns-auth.sh
    - aloeil-duckdns-clean.sh

- name: "Create certbot renew crontab job"
  ansible.builtin.cron:
    name: "certbot_renew"
    minute: 0
    hour: 4
    job: "/compose/nginx/data/script/aloeil-certbot-renew.sh"

- name: "Create certbot certs"
  ansible.builtin.shell:
    cmd: "/compose/nginx/data/script/aloeil-certbot-create.sh"
