---
- name: "Setup or update common"
  hosts: all
  roles:
    - common

- name: "Setup or update rpi2b"
  hosts: rpi2b
  roles:
    - traefik
    - wireguard
    - upsnap
    - dashboard

- name: "Setup or update rpi4"
  hosts: rpi4
  roles:
    - app/homeassistant
