---
- name: "Install common packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - docker-compose

- name: "Create appropriate directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - /compose

- name: "Allow SSH keys for each user"
  ansible.builtin.authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
    comment: "{{ item.name }}"
    "exclusive": "{{ item.exclusive }}"
    state: "present"
  loop_control:
    label: "{{ item.user }}:{{ item.name }}:{{ item.exclusive }}"
  loop: |
    [
    {%- for user in common_users %}
    {%- for key in user.ssh_keys %}
      {
        "user": "{{ user.user }}",
        "key": "{{ key.key }}",
        "name": "{{ key.name }}",
        "exclusive": "{{ loop.index0 == 0 }}",
      },{%- endfor %}
    {%- endfor %}
    ]

- name: "Create ssh config file"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/ssh/sshd_config.d/{{ item }}"
    mode: '0644'
  loop:
    - "10-secure_ssh.conf"
