---
- name: "Create root directory"
  ansible.builtin.file:
    path: "/compose/wireguard/{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - ''

- name: "Create applicative directory"
  ansible.builtin.file:
    path: "/compose/wireguard/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - bind/
    - bind/etc/

- name: "Create compose file"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "/compose/wireguard/docker-compose.yml"
    mode: '0600'
